apiVersion: apps/v1
kind: Deployment
metadata:
  name: zah-sampleapp-deployment-app
  labels:
    app: zah-sampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zah-sampleapp
  template:
    metadata:
      labels:
        app: zah-sampleapp
    spec:
      containers:
        - name: final-task
          image: zah-sampleapp:main
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          envFrom:
            - secretRef:
                name: zah-sampleapp-postgres-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "2"