apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      initContainers:
        - name: sampleapp-migrate
          image: minerva45/sampleapp:main
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: zah-sampleapp-postgres-secret
          command:
            - python
            - manage.py
            - migrate
      