apiVersion: apps/v1
kind: Deployment
metadata:
  name: zah-sampleapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zah-sampleapp
  template:
    metadata:
      labels:
        app: zah-sampleapp
    spec:
      initContainers:
        - name: zah-sampleapp-migrate
          image: minerva45/sampleapp:latest
          ports:
            - containerPort: 8001
          envFrom:
            - secretRef:
                name: zah-sampleapp-postgres-secret
          command:
            - python
            - manage.py
            - migrate
      containers:
        - name: zah-sampleapp
          image: minerva45/sampleapp:latest
          ports:
            - containerPort: 8001
          command: 
            - python
            - manage.py
            - runserver
            - 0.0.0.0:8001
          envFrom:
            - secretRef:
                name: zah-sampleapp-postgres-secret