apiVersion: apps/v1
kind: Deployment
metadata:
  name: zah-sampleapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zah-sampleapp
  template:
    metadata:
      labels:
        app: zah-sampleapp
    spec:
      initContainers:
        - name: zah-sampleapp-migrate
          image: minerva45/sampleapp:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: zah-sampleapp-postgres-secret
          
      containers:
        - name: zah-sampleapp
          image: minerva45/sampleapp:latest
          ports:
            - containerPort: 8000
          
          envFrom:
            - secretRef:
                name: zah-sampleapp-postgres-secret