apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      initContainers:
        - name: sampleapp-migrate
          image: zah/sampleapp:main
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: sampleapp-secret
          command:
            - python
            - manage.py
            - migrate
      containers:
        - name: sampleapp
          image: zah/sampleapp:main
          ports:
            - containerPort: 8000
          command: 
            - python
            - manage.py
            - runserver
            - 0.0.0.0:8000
          envFrom:
            - secretRef:
                name: sampleapp-secret