apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - secret.yaml
  - ingress.yaml

images:
  - name: minerva45/sampleapp
