apiVersion: v1
kind: Service
metadata:
  name: zah-sampleapp-service
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: zah-sampleapp
  type: ClusterIP