

services:
  sampleapp:
    restart: always
    image: sampleapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    tty: true
    environment:
      PYTHONUNBUFFERED: 1
      
    env_file:
      - .env
    command: 
      - python manage.py runserver 0.0.0.0:8000
     
  migrate:
    restart: never
    image: sampleapp:latest
    profiles:
      - migrate
    tty: true
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - .env
    command: 
      - python manage.py migrate
  db:
    image: postgres:15.2
    restart: always
    env_file:
      - .env
    

   

  
