version: '3'

tasks:

  start:
    cmds:
      - task: up
      - task: migrate

  up:
    cmds:
      - docker compose up -d

  migrate:
    cmds:
      - docker compose run migrate

  down:
    cmds:
      - docker compose down

  stop:
    deps:
      - down