apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zah-devops-final-task-certificate
  namespace: zah-devops-final-task
spec:
  dnsNames:
  - 'zah.dacdevops.ru'
  issuerRef:
    kind: ClusterIssuer
    name: yc-clusterissuer
  secretName: zah-devops-final-task-cert