apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zah-sampleapp-certificate
spec:
  dnsNames:
  - 'zah.dacdevops.ru'
  issuerRef:
    kind: ClusterIssuer
    name: yc-clusterissuer
  secretName: zah-sampleapp-cert