apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zah-final-task-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: zah.dacdevops.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zah-final-task-service
                port:
                  name: http
  tls:
    - hosts:
      - zah.dacdevops.ru
      secretName: zah-final-task-cert
