apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: sampleapp:main
    newName: minerva45/sampleapp:main
    newTag: v1.1.1

resources:
- ../../base
- ingress.yaml
- namespace.yaml
- certificate.yaml