apiVersion: apps/v1
kind: Deployment
metadata:
  name: zah-final-task-deployment-postgres
  labels:
    app: zah-final-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zah-final-task-postgres
  template:
    metadata:
      labels:
        app: zah-final-task-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.1
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: zah-final-task-postgres-secret
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "1"
