apiVersion: v1
kind: Service
metadata:
  name: zah-devops-final-task-service-postgres
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: zah-devops-final-task
  type: ClusterIP