apiVersion: v1
kind: Service
metadata:
  name: zah-sampleapp-service-postgres
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: zah-sampleapp
  type: ClusterIP